# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formAddCity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 100)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditAddChangeCity = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAddChangeCity.sizePolicy().hasHeightForWidth())
        self.lineEditAddChangeCity.setSizePolicy(sizePolicy)
        self.lineEditAddChangeCity.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAddChangeCity.setFont(font)
        self.lineEditAddChangeCity.setObjectName("lineEditAddChangeCity")
        self.gridLayout.addWidget(self.lineEditAddChangeCity, 0, 0, 1, 1)
        self.pushButtonAddChangeCity = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddChangeCity.sizePolicy().hasHeightForWidth())
        self.pushButtonAddChangeCity.setSizePolicy(sizePolicy)
        self.pushButtonAddChangeCity.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddChangeCity.setFont(font)
        self.pushButtonAddChangeCity.setObjectName("pushButtonAddChangeCity")
        self.gridLayout.addWidget(self.pushButtonAddChangeCity, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить нас.пункт"))
        self.pushButtonAddChangeCity.setText(_translate("Dialog", "Добавить/Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
